# Generated by Django 4.2 on 2024-01-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isview',
            field=models.BooleanField(default=True, verbose_name='Görüntüle'),
        ),
    ]
